# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-on-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - run: mvn --no-transfer-progress -Pbuild-on-ubuntu clean install jpackage:jpackage
    - run: ls -al target/dist
    - uses: actions/upload-artifact@v4
      with:
        path: ./target/dist/visualizer_1.0.0_amd64.deb
        name: linux-installer.deb
        retention-days: 1
        if-no-files-found: error
  
  build-on-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - run: mvn --no-transfer-progress -Pbuild-on-mac clean install jpackage:jpackage
    - run: ls -al target/dist
    - uses: actions/upload-artifact@v4
      with:
        path: ./target/dist/Visualizer-1.0.0.dmg
        name: macos-installer.dmg
        retention-days: 1
        if-no-files-found: error

  build-on-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - run: mvn --no-transfer-progress -Pbuild-on-windows clean install jpackage:jpackage
    - run: dir target/dist
    - uses: actions/upload-artifact@v4
      with:
        path: ./target/dist/Visualizer-1.0.0.exe
        name: windows-installer.exe
        retention-days: 1
        if-no-files-found: error
